### PR TITLE
Tests fixed to be aware different decimal separators by cultures

### LINKED ISSUE #39: PowerShell tests doesn't care about regional settings for a decimal separator
If a decimal separator is not '.' (dot) but ',' (comma) than some Pester tests for PScribo fail due to hardcoded patern (?)

Tested with the current PScribo dev branch - the last commit a9b024eda4bccc0a84f3ba168f8bc21fcd5683c1 .

```powershell
Describing OutHtml.Internal\GetHtmlTableStyle
   Context By Named Parameter.
    [-] creates default table style. 137ms
      String lengths are both 24. Strings differ at index 1.
      Expected: {0.08em 0.33em 0em 0.33em}
      But was:  {0,08em 0,33em 0em 0,33em}
      ------------^
      184:                 ($padding.Split(':').Trim())[1] | Should BeExactly '0.08em 0.33em 0em 0.33em';
      at <ScriptBlock>, C:\Users\<SOME_FOLDER>\PScribo\Tests\Plugins\OutHtml.Tests.ps1: line 184
    [-] creates custom table padding style of 5pt, 10pt, 5pt and 10pt. 64ms
      String lengths are both 27. Strings differ at index 1.
      Expected: {0.42em 0.83em 0.42em 0.83em}
      But was:  {0,42em 0,83em 0,42em 0,83em}
      ------------^
      200:                 ($padding.Split(':').Trim())[1] | Should BeExactly '0.42em 0.83em 0.42em 0.83em';
      at <ScriptBlock>, C:\Users\<SOME_FOLDER>\PScribo\Tests\Plugins\OutHtml.Tests.ps1: line 200
    [+] creates custom table border color style when -BorderWidth is specified. 63ms
    [-] creates custom table border width style of 3pt. 45ms
      String lengths are both 6. Strings differ at index 1.
      Expected: {0.25em}
      But was:  {0,25em}
      ------------^
      218:                 ($borderWidth.Split(':').Trim())[1] | Should BeExactly '0.25em';
      at <ScriptBlock>, C:\Users\<SOME_FOLDER>\PScribo\Tests\Plugins\OutHtml.Tests.ps1: line 218
    [+] creates custom table border with no color style when no -BorderWidth specified. 61ms
    [+] creates custom table border color style. 34ms
    [+] centers table. 34ms
    [+] aligns table to the right. 33ms
```

Probably helpful link: https://technet.microsoft.com/en-us/library/ff730954.aspx

### PR DESCRIPTION
**Pull request by it-praktyk**
Fix #39

### CODE REVIEW

**Comment by iainbrighton** [comment]
@it-praktyk Thanks for the PR.

Question - do you know whether CSS style decimals are culture insensitive? By this I mean is 0,42em a valid CSS property? Obviously this will have a bearing on whether we need to fix the tests or actually fix the code!

**Comment by iainbrighton** [comment]
@it-praktyk Looking here - one of these lines should be removed https://github.com/iainbrighton/PScribo/blob/dev/Src/Plugins/OutHtml.Internal.ps1#L44-L45 - probably line 45! I think line 44 should always give the same result?

Any chance you can remove line 45 and rerun the tests without your changes?

**Comment by iainbrighton** [comment]
Also it looks like the decimals have be specified with a decimal point and not a comma. Looks at the "Invalid property value" [here](https://github.com/iainbrighton/PScribo/issues/6).

**Comment by it-praktyk** [comment]
Even after removing the line 45 tests fail.

Yes, probably replacing dots with commas was not the correct idea to resolve that issue, so I'm closing my pull request.

**Comment by iainbrighton** [comment]
@it-praktyk OK - I've managed to [recreate this with this](https://blogs.msdn.microsoft.com/powershell/2006/04/25/using-culture-culture-culture-script-scriptblock/) and calling Invoke-Pester 😄. I can see that removing that line did help - that one test - but not the others. I'll get this fixed!

**Pull request closed without merging**
