### PR TITLE
Add Image support

### PR DESCRIPTION
**Pull request by matt2005**
Added Support for images in Word.

### CODE REVIEW

**Comment by iainbrighton** [comment]
@matt2005 An awesome contribution! Couple of things:

* There appears to be no test coverage for the new methods.
  * Can you add some tests for the new image functions?
* I'm struggling to digest all the changes as the bracing style and spacing has changed (from 4 spaces to 2 spaces). 
  * This means that I'll probably need to merge it into a separate branch before merging into dev. Are you happy to resubmit the PR into the `Image` branch?

**Comment by matt2005** [comment]
-  I have some tests written, I just haven't completed them yet. 

- This is due to ISESteroids Auto-format. Do you want me to redo my changes without putting it thorough auto format?

**Comment by iainbrighton** [comment]
@matt2005 You can run the tests by running `Invoke-Pester -Script .\Tests`. The VirtualEngine.Build module is only needed when packaging/building the module for release/publishing.

Don't worry about reformatting as I can get VSCode to do this for me. If you can push your PR to the [Image](https://github.com/iainbrighton/PScribo/tree/Image) branch, we can work on it there?

Thanks for your contribution 😃!

**Comment by matt2005** [comment]
Resubmitted into image branch #52

**Pull request closed without merging**
